version: '3.8'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

  web:
    image: stranix34/kfc_support_bot:latest
    restart: unless-stopped
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    extra_hosts:
      - "sd.irb.rest:83.217.25.60"
    expose:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    command: gunicorn --bind 0.0.0.0:8000 config.asgi -w 4 -k uvicorn.workers.UvicornWorker

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
     - ./nginx:/etc/nginx/templates
     - static_volume:/home/app/web/static
     - media_volume:/home/app/web/media
    ports:
     - "1337:80"
    environment:
     - NGINX_PORT=80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  postgres_data:
  redis_data: