# Generated by Django 4.2.4 on 2023-09-18 09:52

from django.db import migrations


def add_default_server_types_and_franchises(apps, schema_editor):
    """
    Заполняем типы серверов и франшизы
    """
    server_types = [
        'Referents',
        'SuperTransit',
        'Transit',
        'Report',
        'MidServer',
    ]
    franchises = [
        ('UniRest', 'yum'),
        ('IRB', 'irb'),
        ('FZ', 'fz'),
    ]

    ServerType = apps.get_model('src', 'ServerType')
    FranchiseOwner = apps.get_model('src', 'FranchiseOwner')

    for server_type in server_types:
        ServerType.objects.update_or_create(name=server_type)

    for franchise_name, franchise_alias in franchises:
        FranchiseOwner.objects.update_or_create(
            name=franchise_name,
            alias=franchise_alias
        )


class Migration(migrations.Migration):
    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_server_types_and_franchises),
    ]
