# Generated by Django 4.2.4 on 2023-09-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20230901_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ident',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='RK ident'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='server_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP главного сервера RK'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Номер телефона ресторана'),
        ),
    ]
