# Generated by Django 4.2.4 on 2023-09-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_syncreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncreport',
            options={'verbose_name': 'Журнал синхронизации', 'verbose_name_plural': 'Журналы синхронизации'},
        ),
        migrations.AddField(
            model_name='syncreport',
            name='user_choice',
            field=models.CharField(default='all', max_length=25, verbose_name='Выбор пользователя'),
            preserve_default=False,
        ),
    ]
