# Generated by Django 4.2.4 on 2023-09-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_restaurant_ident_restaurant_server_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='ident',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ident',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='RK ident'),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='RK ident'),
        ),
    ]
