# Generated by Django 4.2.4 on 2023-09-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_syncreport_options_syncreport_user_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ext_name',
            field=models.CharField(default='', max_length=50, verbose_name='Расширенное имя'),
        ),
    ]
