# Generated by Django 4.2.4 on 2023-10-02 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_employee_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='managers',
            field=models.ManyToManyField(blank=True, to='src.employee', verbose_name='Менеджеры'),
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start_at', models.DateTimeField(verbose_name='Старт смены')),
                ('shift_start_break_at', models.DateTimeField(blank=True, null=True, verbose_name='Старт перерыва')),
                ('shift_end_break_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение перерыва')),
                ('shift_end_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение смены')),
                ('is_works', models.BooleanField(default=True, verbose_name='Работает?')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_shifts', to='src.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Рабочая Смена',
                'verbose_name_plural': 'Рабочие Смены',
            },
        ),
    ]
