# Generated by Django 4.2.4 on 2023-10-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_employee_managers_workshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tg_nickname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ник в телеге'),
        ),
    ]
