# Generated by Django 4.2.4 on 2023-10-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_botcommand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshift',
            name='shift_end_break_at',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='shift_start_break_at',
        ),
        migrations.CreateModel(
            name='BreakShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_break_at', models.DateTimeField(auto_now_add=True, verbose_name='Старт перерыва')),
                ('end_break_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение перерыва')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='break_shifts', to='src.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Перерыв',
                'verbose_name_plural': 'Перерывы',
            },
        ),
        migrations.AddField(
            model_name='workshift',
            name='break_shift',
            field=models.ManyToManyField(blank=True, related_name='work_shifts', to='src.breakshift', verbose_name='Перерывы'),
        ),
    ]
