# Generated by Django 4.2.7 on 2023-11-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_alter_employee_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCommandCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Категория Команды Бота',
                'verbose_name_plural': 'Категории Команды Бота',
            },
        ),
        migrations.AddField(
            model_name='botcommand',
            name='view_priority',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядок вывода команды'),
        ),
        migrations.AddField(
            model_name='botcommand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_bot_commands', to='src.botcommandcategory', verbose_name='Доступна для групп'),
        ),
    ]
