# Generated by Django 4.2.7 on 2023-11-07 10:41

from django.db import migrations


def add_bot_command_category(apps, schema_editor):
    """
    Заполняем группы доступа
    """
    categories = [
        'Шедулер',
        'Синхронизация',
        'Задачи',
        'Рабочие Смены',
        'Запрос Поддержки',
    ]

    command_category = apps.get_model('src', 'BotCommandCategory')

    for category_name in categories:
        command_category.objects.update_or_create(name=category_name)


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_botcommandcategory_botcommand_view_priority_and_more'),
    ]

    operations = [
        migrations.RunPython(add_bot_command_category),
    ]
