# Generated by Django 4.2.7 on 2023-11-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_auto_20231107_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='support_group',
            field=models.CharField(choices=[('DISPATCHER', 'Диспетчера'), ('ENGINEER', 'Инженеры')], db_index=True, default='DISPATCHER', max_length=10, verbose_name='Помощь от '),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Низкий'), ('MID', 'Средний'), ('HIGH', 'Высокий'), ('CRITICAL', 'Критичный')], default='', max_length=20, null=True, verbose_name='Приоритет'),
        ),
    ]
