# Generated by Django 4.2.7 on 2023-11-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_task_support_group_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='closing_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий закрытия'),
        ),
        migrations.AddField(
            model_name='task',
            name='doc_path',
            field=models.TextField(blank=True, null=True, verbose_name='Пути сохраненных файлов'),
        ),
        migrations.AddField(
            model_name='task',
            name='sub_task_number',
            field=models.TextField(blank=True, null=True, verbose_name='Список дочерних задач'),
        ),
    ]
