# Generated by Django 4.2.7 on 2023-11-21 10:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_auto_20231115_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSDTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=100, verbose_name='Заявитель')),
                ('number', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Номер заявки GSD')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок обработки')),
                ('service', models.CharField(max_length=100, verbose_name='Услуга')),
                ('gsd_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='Группа GSD')),
                ('title', models.CharField(max_length=150, verbose_name='Тема обращения')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gsd_tasks', to='src.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Задача GSD',
                'verbose_name_plural': 'Задачи GSD',
            },
        ),
        migrations.DeleteModel(
            name='TaskComment',
        ),
    ]
