# Generated by Django 4.2.7 on 2023-11-21 10:08

from django.db import migrations


def move_tasks_to_gsd_tasks(apps, schema_editor):
    """
    Переносим информацию о записанных задачах GSD в таблицу GSDTask
    """

    Task = apps.get_model('src', 'Task')
    GSDTask = apps.get_model('src', 'GSDTask')

    for task in Task.objects.iterator():
        if task.number.find('SD') != -1:
            continue
        GSDTask.objects.create(
            applicant=task.applicant,
            number=task.number,
            restaurant=task.restaurant,
            start_at=task.start_at,
            expired_at=task.expired_at,
            service=task.service,
            title=task.title,
            description=task.description,
            gsd_group=task.gsd_group,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('src', '0020_gsdtask_delete_taskcomment'),
    ]

    operations = [
        migrations.RunPython(move_tasks_to_gsd_tasks),
    ]
