# Generated by Django 4.2.7 on 2023-11-21 12:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0021_auto_20231121_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=100, verbose_name='Заявитель')),
                ('number', models.CharField(db_index=True, max_length=10, verbose_name='Номер заявки SD')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('finish_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('support_group', models.CharField(choices=[('DISPATCHER', 'Диспетчера'), ('ENGINEER', 'Инженеры')], db_index=True, default='DISPATCHER', max_length=10, verbose_name='Помощь от ')),
                ('title', models.CharField(max_length=150, verbose_name='Тема обращения')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('ASSIGNED', 'Назначена'), ('IN_WORK', 'В работе'), ('COMPLETED', 'Завершена')], db_index=True, default='NEW', max_length=20, verbose_name='Статус')),
                ('closing_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий закрытия')),
                ('sub_task_number', models.TextField(blank=True, null=True, verbose_name='Список дочерних задач')),
                ('doc_path', models.TextField(blank=True, null=True, verbose_name='Пути сохраненных файлов')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sd_tasks', to='src.employee', verbose_name='Исполнитель')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sd_tasks', to='src.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Задача Поддержки',
                'verbose_name_plural': 'Задачи Поддержки',
            },
        ),
    ]
