# Generated by Django 4.2.7 on 2023-11-21 12:26

from django.db import migrations


def move_tasks_to_sd_tasks(apps, schema_editor):
    """
    Переносим информацию о записанных задачах GSD в таблицу GSDTask
    """

    Task = apps.get_model('src', 'Task')
    SDTask = apps.get_model('src', 'SDTask')

    for task in Task.objects.iterator():
        if task.number.find('SС') != -1:
            continue
        SDTask.objects.create(
            applicant=task.applicant,
            number=task.number,
            performer=task.performer,
            start_at=task.start_at,
            finish_at=task.finish_at,
            support_group=task.support_group,
            title=task.title,
            description=task.description,
            status=task.status,
            closing_comment=task.closing_comment,
            sub_task_number=task.sub_task_number,
            doc_path=task.doc_path,
            rating=task.rating,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0022_sdtask'),
    ]

    operations = [
        migrations.RunPython(move_tasks_to_sd_tasks),
    ]
