# Generated by Django 4.2.7 on 2023-11-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0023_auto_20231121_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
