# Generated by Django 4.2.7 on 2023-11-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0024_delete_task'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE src_sdtask_id_seq RESTART WITH 50000;'
        )
    ]
