# Generated by Django 4.2.7 on 2023-11-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0025_auto_20231121_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdtask',
            name='tmp_applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_sd_tasks', to='src.employee', verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='employees', to='src.group', verbose_name='Группа доступа'),
        ),
    ]
