# Generated by Django 4.2.7 on 2023-11-29 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0027_auto_20231129_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdtask',
            name='applicant',
        ),
        migrations.AlterField(
            model_name='sdtask',
            name='tmp_applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicant_sd_tasks', to='src.employee', verbose_name='Заявитель'),
        ),
    ]
