# Generated by Django 4.2.8 on 2023-12-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0029_rename_tmp_applicant_sdtask_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, default='', max_length=100, verbose_name='Компания')),
                ('restaurant', models.CharField(blank=True, default='', max_length=100, verbose_name='Ресторан')),
                ('gsd_numbers', models.CharField(blank=True, default='', max_length=100, verbose_name='Связанные заявки GSD')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatcher_tasks', to='src.employee', verbose_name='Исполнитель')),
            ],
        ),
    ]
