# Generated by Django 4.2.8 on 2023-12-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0030_employee_dispatcher_name_sdtask_is_automatic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcher',
            name='tg_documents',
            field=models.TextField(blank=True, null=True, verbose_name='Документы'),
        ),
    ]
