# Generated by Django 4.2.8 on 2023-12-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0030_dispatcher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatcher',
            options={'verbose_name': 'Задача из Диспетчера', 'verbose_name_plural': 'Задачи из Диспетчера'},
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='closing_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий закрытия'),
        ),
        migrations.AddField(
            model_name='employee',
            name='dispatcher_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя в диспетчере'),
        ),
    ]
