# Generated by Django 4.2.8 on 2023-12-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0031_dispatcher_tg_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcher',
            name='dispatcher_number',
            field=models.PositiveIntegerField(verbose_name='Номер в диспетчере'),
        ),
    ]
