# Generated by Django 4.2.8 on 2023-12-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0032_alter_dispatcher_dispatcher_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcher',
            name='itsm_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер ITSM'),
        ),
    ]
