# Generated by Django 4.2.8 on 2024-02-01 17:56

from django.db import migrations


def move_groups(apps, schema_editor):
    """
    Переносим старые группы в группы django
    """
    CustomGroup = apps.get_model('src', 'CustomGroup')
    Group = apps.get_model('src', 'Group')

    for group in Group.objects.iterator():
        new_group, _ = CustomGroup.objects.update_or_create(
            name=group.name,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0035_customgroup'),
    ]

    operations = [
        migrations.RunPython(move_groups),
    ]
