# Generated by Django 4.2.8 on 2024-02-01 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0037_auto_20240201_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdtask',
            name='new_applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_applicant_sd_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель(Новый)'),
        ),
        migrations.AddField(
            model_name='sdtask',
            name='new_performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_sd_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель(Новый)'),
        ),
    ]
