# Generated by Django 4.2.8 on 2024-02-02 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0039_edit_applicant_performer_in_sd_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcher',
            name='new_performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_dispatcher_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель(Новый)'),
        ),
    ]
