# Generated by Django 4.2.8 on 2024-02-02 12:03

from django.db import migrations


def edit_employee_in_break_shift(apps, _):
    """
    Меняем привязку пользователей в информации о перерывах
    Employee -> CustomUser
    """
    CustomUser = apps.get_model('src', 'CustomUser')
    BreakShift = apps.get_model('src', 'BreakShift')

    for break_shift in BreakShift.objects.iterator():
        try:
            break_shift_employee = CustomUser.objects.get(
                name=break_shift.employee.name,
            )
            break_shift.new_employee = break_shift_employee
            break_shift.save()
        except CustomUser.DoesNotExist:
            print('Перерывы. Проблема с записью id:', break_shift.id)
        except AttributeError:
            print('Перерывы(a). Проблема с записью id:', break_shift.id)


class Migration(migrations.Migration):
    dependencies = [
        ('src', '0042_breakshift_new_employee'),
    ]

    operations = [
        migrations.RunPython(edit_employee_in_break_shift),
    ]
