# Generated by Django 4.2.8 on 2024-02-02 12:23

from django.db import migrations


def edit_employee_in_work_shift(apps, _):
    """
    Меняем привязку пользователей в информации о сменах
    Employee -> CustomUser
    """
    CustomUser = apps.get_model('src', 'CustomUser')
    WorkShift = apps.get_model('src', 'WorkShift')

    for work_shift in WorkShift.objects.iterator():
        try:
            work_shift_employee = CustomUser.objects.get(
                name=work_shift.employee.name,
            )
            work_shift.new_employee = work_shift_employee
            work_shift.save()
        except CustomUser.DoesNotExist:
            print('Перерывы. Проблема с записью id:', work_shift.id)
        except AttributeError:
            print('Перерывы(a). Проблема с записью id:', work_shift.id)


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0044_workshift_new_employee'),
    ]

    operations = [
        migrations.RunPython(edit_employee_in_work_shift),
    ]
