# Generated by Django 4.2.8 on 2024-02-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0047_edit_employee_in_sync_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='botcommand',
            name='new_groups',
            field=models.ManyToManyField(blank=True, related_name='new_bot_commands', to='src.customgroup', verbose_name='Доступна для групп(Новая)'),
        ),
    ]
