# Generated by Django 4.2.8 on 2024-02-02 13:25

from django.db import migrations


def edit_groups_in_bot_command(apps, _):
    """
    Меняем привязку пользователей в информации о сменах
    Employee -> CustomUser
    """
    CustomGroup = apps.get_model('src', 'CustomGroup')
    BotCommand = apps.get_model('src', 'BotCommand')

    for bot_command in BotCommand.objects.iterator():
        for bot_group in bot_command.groups.all():
            try:
                new_bot_group = CustomGroup.objects.get(name=bot_group.name)
                bot_command.new_groups.add(new_bot_group)
            except CustomGroup.DoesNotExist:
                print('Проблема с группой ', bot_group.name)
        bot_command.save()


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0048_botcommand_new_groups'),
    ]

    operations = [
        migrations.RunPython(edit_groups_in_bot_command),
    ]
