# Generated by Django 4.2.8 on 2024-02-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0049_edit_groups_in_bot_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='employees', to='src.customgroup', verbose_name='Менеджеры'),
        ),
    ]
