# Generated by Django 4.2.8 on 2024-02-06 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0051_alter_botcommand_category_alter_syncreport_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakshift',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='break_shifts', to='src.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_shifts', to='src.employee', verbose_name='Сотрудник'),
        ),
    ]
