# Generated by Django 4.2.8 on 2024-02-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0053_alter_customuser_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи (Новые)'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи (Архив)'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа доступа', 'verbose_name_plural': 'Группы доступа(Архив)'},
        ),
    ]
