# Generated by Django 4.2.8 on 2024-02-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0054_alter_customuser_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botcommand',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='groups',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
