# Generated by Django 4.2.8 on 2024-02-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0055_remove_botcommand_groups_remove_employee_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatcher',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatcher_tasks', to='src.employee', verbose_name='Исполнитель'),
        ),
    ]
