# Generated by Django 4.2.8 on 2024-02-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0056_alter_dispatcher_performer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
