# Generated by Django 4.2.8 on 2024-02-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0057_alter_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdtask',
            name='is_close_task_command',
            field=models.BooleanField(default=False, verbose_name='Команда закрытия задачи?'),
        ),
        migrations.AddField(
            model_name='sdtask',
            name='tg_docs',
            field=models.TextField(blank=True, null=True, verbose_name='Телеграм Документы'),
        ),
    ]
