# Generated by Django 4.2.8 on 2024-03-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0058_sdtask_is_close_task_command_sdtask_tg_docs'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customgroup',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='dispatcher',
            name='simpleone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Связанные заявки SimpleOne'),
        ),
    ]
