# Generated by Django 4.2.8 on 2024-03-20 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0059_alter_customgroup_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleOneCIService',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Сервис SimpleOne',
                'verbose_name_plural': 'Сервисы SimpleOne',
            },
        ),
        migrations.CreateModel(
            name='SimpleOneCompany',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Компания SimpleOne',
                'verbose_name_plural': 'Компании SimpleOne',
            },
        ),
        migrations.CreateModel(
            name='SimpleOneCred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('token', models.TextField(verbose_name='Token')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Получен')),
                ('expired_at', models.DateTimeField(verbose_name='Истекает')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleOneIRBDepartment',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField()),
                ('ext_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='Внешний код')),
            ],
            options={
                'verbose_name': 'Департамент IRB SimpleOne',
                'verbose_name_plural': 'Департаменты IRB SimpleOne',
            },
        ),
        migrations.CreateModel(
            name='SimpleOneRequestType',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Тип запроса SimpleOne',
                'verbose_name_plural': 'Типы запросов SimpleOne',
            },
        ),
        migrations.CreateModel(
            name='SimpleOneSupportGroup',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Группа поддержки SimpleOne',
                'verbose_name_plural': 'Группы поддержки SimpleOne',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_guid',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ext_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Внешний код'),
        ),
        migrations.CreateModel(
            name='SimpleOneTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_group_link', models.TextField(verbose_name='Сcылка на группу в api')),
                ('company_link', models.TextField(verbose_name='Сcылка на компанию в api')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('number', models.CharField(max_length=15, verbose_name='Номер задачи')),
                ('fact_start', models.DateTimeField(verbose_name='Старт задачи')),
                ('service_link', models.TextField(verbose_name='Ссылка на сервис в api')),
                ('subject', models.TextField(verbose_name='Тема Обращения')),
                ('sys_id', models.PositiveIntegerField(verbose_name='Id Задачи в simple')),
                ('caller_department_link', models.TextField(verbose_name='Ссылка на ресторан в api')),
                ('contact_information', models.TextField(verbose_name='Контакты')),
                ('sla', models.CharField(blank=True, max_length=10, null=True, verbose_name='SLA')),
                ('exp_sla', models.DateTimeField(blank=True, null=True, verbose_name='Выполнить до')),
                ('request_type_link', models.TextField(verbose_name='Сcылка на проблему в api')),
                ('request_type', models.TextField(verbose_name='Проблема')),
                ('api_path', models.TextField(verbose_name='Путь к задачи')),
                ('caller_department', models.TextField(verbose_name='Заявитель')),
                ('service', models.TextField(verbose_name='Сервис')),
                ('company', models.TextField(verbose_name='Компания заявителя')),
                ('assignment_group', models.TextField(verbose_name='Группа назначения')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simpleone_tasks', to='src.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Задача SimpleOne',
                'verbose_name_plural': 'Задачи SimpleOne',
            },
        ),
    ]
