# Generated by Django 4.2.11 on 2024-03-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0062_alter_simpleonetask_sys_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleonetask',
            name='description',
            field=models.TextField(default='-', verbose_name='Описание задачи'),
        ),
    ]
