# Generated by Django 4.2.11 on 2024-03-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0063_alter_simpleonetask_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleonetask',
            name='description',
            field=models.TextField(default='-', null=True, verbose_name='Описание задачи'),
        ),
    ]
