# Generated by Django 4.2.11 on 2024-08-08 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0064_alter_simpleonetask_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGDeepLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deeplink_key', models.CharField(max_length=5, verbose_name='Ключ')),
                ('deeplink', models.CharField(max_length=150, verbose_name='Ссылка')),
                ('creat_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deeplink', to='src.customgroup', verbose_name='Группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deeplinks', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'TGDeepLink',
                'verbose_name_plural': 'TGDeepLinks',
            },
        ),
    ]
