# Generated by Django 4.2.11 on 2024-08-08 17:06

from django.db import migrations


def create_new_bot_command(apps, schema_editor):
    """
    Двигаем пользователей из модели Employee в кастомную модель
    пользователей Django CustomUser
    """
    BotCommand = apps.get_model('src', 'BotCommand')
    BotCommandCategory = apps.get_model('src', 'BotCommandCategory')
    support_category = BotCommandCategory.objects.get(name='Запрос Поддержки')
    BotCommand.objects.create(
        name='/help_sber',
        description='Запрос помощи инженера поддержки',
        category=support_category,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('src', '0065_tgdeeplink'),
    ]

    operations = [
        migrations.RunPython(create_new_bot_command),
    ]
