on:
  push:
    branches: [ "new-version" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USER }}/kfc_support_bot

jobs:
    publish:
        name: publish image
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: create-json
          id: create-json
          uses: jsdaniell/create-json@v1.2.3
          with:
            name: "logging_config.json"
            json: ${{ secrets.LOGGING_JSON }}
            dir: "config/"
        - run: git config --global user.email "phantom2525@gmail.com" && git config --global user.name "Stranix" && git add . && git add --force config/logging_config.json && git status && git commit -a -m "Deploy HCommit with the logging JSON created!"
        - name: Login
          run: |
            echo ${{ secrets.PAT }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        - name: Build and Publish
          run: |
            cat config/logging_config.json
            version=$(grep -m 1 version pyproject.toml | tr -s ' ' | tr -d '"' | tr -d "'" | cut -d' ' -f3)
            docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$version --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$version
            docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

    deploy:
      needs: publish
      name: deploy image
      runs-on: ubuntu-latest

      steps:
        - name: install ssh keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        - name: connect and pull
          run: ssh -p 5022 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && ./docker_deploy.sh && exit"
        - name: cleanup
          run: rm -rf ~/.ssh